//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.3pay.com/services/", ConfigurationName="SaleService.SaleServiceSoap")]
    public interface SaleServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.3pay.com/services/SaleWithConfirm", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MSaleInput1))]
        System.Threading.Tasks.Task<SaleService.MSaleOutput> SaleWithConfirmAsync(SaleService.MAuthToken token, SaleService.MSaleInput input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.3pay.com/services/SaleWithoutConfirm", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MSaleInput1))]
        System.Threading.Tasks.Task<SaleService.MSaleOutput> SaleWithoutConfirmAsync(SaleService.MAuthToken token, SaleService.MSaleInput input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.3pay.com/services/SaleWithoutConfirmTest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MSaleInput1))]
        System.Threading.Tasks.Task<SaleService.MSaleOutput> SaleWithoutConfirmTestAsync(SaleService.MAuthToken token, SaleService.MSaleInput input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.3pay.com/services/GetSaleResult", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MSaleInput1))]
        System.Threading.Tasks.Task<SaleService.MSaleOutput> GetSaleResultAsync(SaleService.MAuthToken token, System.Guid orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.3pay.com/services/GetSaleResultMPAY", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MSaleInput1))]
        System.Threading.Tasks.Task<SaleService.MSaleOutput> GetSaleResultMPAYAsync(SaleService.MAuthToken token, string MPAY);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.3pay.com/services/GetSaleResult2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MSaleInput1))]
        System.Threading.Tasks.Task<SaleService.MSaleResult> GetSaleResult2Async(SaleService.MAuthToken token, System.Guid orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.3pay.com/services/QueryMicroPayments", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MSaleInput1))]
        System.Threading.Tasks.Task<SaleService.MQueryOutput> QueryMicroPaymentsAsync(SaleService.MAuthToken token, SaleService.MQueryInput input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.3pay.com/services/SaleWithTicket", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MSaleInput1))]
        System.Threading.Tasks.Task<SaleService.MSaleTicketOutput> SaleWithTicketAsync(SaleService.MAuthToken token, SaleService.MSaleTicketInput input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.3pay.com/services/SaleWithTicketMP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MSaleInput1))]
        System.Threading.Tasks.Task<SaleService.MSaleTicketOutput> SaleWithTicketMPAsync(SaleService.MAuthToken token, SaleService.MSaleTicketInputExtended input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.3pay.com/services/CancelTicket", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MSaleInput1))]
        System.Threading.Tasks.Task<SaleService.MResult> CancelTicketAsync(SaleService.MAuthToken token, System.Guid ticketObjectId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.3pay.com/services/CheckTicket", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MSaleInput1))]
        System.Threading.Tasks.Task<SaleService.MResult> CheckTicketAsync(SaleService.MAuthToken token, System.Guid ticketObjectId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.3pay.com/services/GetBokuPricePoints", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MSaleInput1))]
        System.Threading.Tasks.Task<string> GetBokuPricePointsAsync(string country);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.3pay.com/services/CreditCardProxy", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MSaleInput1))]
        System.Threading.Tasks.Task<SaleService.MSaleOutput1> CreditCardProxyAsync(SaleService.MAuthToken1 token, SaleService.CreditCardProxyInput input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.3pay.com/services/StartSaleWithOtp", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MSaleInput1))]
        System.Threading.Tasks.Task<SaleService.MSaleOutput> StartSaleWithOtpAsync(SaleService.MAuthToken token, SaleService.MSaleInput input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.3pay.com/services/ResumeSaleWithOtp", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MSaleInput1))]
        System.Threading.Tasks.Task<SaleService.MSaleOutput> ResumeSaleWithOtpAsync(SaleService.MAuthToken token, System.Guid orderId, string otp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.3pay.com/services/CreateTicketForMsisdnForwarding", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MSaleInput1))]
        System.Threading.Tasks.Task<SaleService.TicketOutput> CreateTicketForMsisdnForwardingAsync(SaleService.MAuthToken token, string redirectUrl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.3pay.com/services/StartSubscriptionWithToken", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MSaleInput1))]
        System.Threading.Tasks.Task<SaleService.MSaleOutputCreditCard> StartSubscriptionWithTokenAsync(SaleService.MAuthToken token, SaleService.MTokenSaleInput input);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.3pay.com/services/")]
    public partial class MAuthToken
    {
        
        private string userCodeField;
        
        private string pinField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserCode
        {
            get
            {
                return this.userCodeField;
            }
            set
            {
                this.userCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Pin
        {
            get
            {
                return this.pinField;
            }
            set
            {
                this.pinField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.3pay.com/services/")]
    public partial class MTokenSaleInput
    {
        
        private System.Guid tokenIdField;
        
        private string mPAYField;
        
        private int paymentTypeIdField;
        
        private string extraField;
        
        private int installmentCountField;
        
        private MSaleProduct[] productListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid tokenId
        {
            get
            {
                return this.tokenIdField;
            }
            set
            {
                this.tokenIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MPAY
        {
            get
            {
                return this.mPAYField;
            }
            set
            {
                this.mPAYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int PaymentTypeId
        {
            get
            {
                return this.paymentTypeIdField;
            }
            set
            {
                this.paymentTypeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Extra
        {
            get
            {
                return this.extraField;
            }
            set
            {
                this.extraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int InstallmentCount
        {
            get
            {
                return this.installmentCountField;
            }
            set
            {
                this.installmentCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        public MSaleProduct[] ProductList
        {
            get
            {
                return this.productListField;
            }
            set
            {
                this.productListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.3pay.com/services/")]
    public partial class MSaleProduct
    {
        
        private int productIdField;
        
        private int productCategoryField;
        
        private string productDescriptionField;
        
        private double priceField;
        
        private int unitField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ProductId
        {
            get
            {
                return this.productIdField;
            }
            set
            {
                this.productIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int ProductCategory
        {
            get
            {
                return this.productCategoryField;
            }
            set
            {
                this.productCategoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ProductDescription
        {
            get
            {
                return this.productDescriptionField;
            }
            set
            {
                this.productDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public double Price
        {
            get
            {
                return this.priceField;
            }
            set
            {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int Unit
        {
            get
            {
                return this.unitField;
            }
            set
            {
                this.unitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="MMicroPaymentOutput", Namespace="http://services.mikro-odeme.com/")]
    public partial class MMicroPaymentOutput1
    {
        
        private System.Guid paymentObjectIdField;
        
        private int statusCodeField;
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid PaymentObjectId
        {
            get
            {
                return this.paymentObjectIdField;
            }
            set
            {
                this.paymentObjectIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int StatusCode
        {
            get
            {
                return this.statusCodeField;
            }
            set
            {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ErrorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ErrorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="MSaleOutput", Namespace="http://services.mikro-odeme.com/")]
    public partial class MSaleOutput1
    {
        
        private System.Guid orderObjectIdField;
        
        private string gsmField;
        
        private int gsmOperatorField;
        
        private int gsmTypeField;
        
        private int stateField;
        
        private int orderChannelIdField;
        
        private int paymentCategoryIdField;
        
        private System.DateTime lastTransactionDateField;
        
        private string mPAYField;
        
        private System.Guid subscriberIdField;
        
        private string pINField;
        
        private MMicroPaymentOutput1[] microPaymentResultsField;
        
        private int statusCodeField;
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid OrderObjectId
        {
            get
            {
                return this.orderObjectIdField;
            }
            set
            {
                this.orderObjectIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Gsm
        {
            get
            {
                return this.gsmField;
            }
            set
            {
                this.gsmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int GsmOperator
        {
            get
            {
                return this.gsmOperatorField;
            }
            set
            {
                this.gsmOperatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int GsmType
        {
            get
            {
                return this.gsmTypeField;
            }
            set
            {
                this.gsmTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int State
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int OrderChannelId
        {
            get
            {
                return this.orderChannelIdField;
            }
            set
            {
                this.orderChannelIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int PaymentCategoryId
        {
            get
            {
                return this.paymentCategoryIdField;
            }
            set
            {
                this.paymentCategoryIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public System.DateTime LastTransactionDate
        {
            get
            {
                return this.lastTransactionDateField;
            }
            set
            {
                this.lastTransactionDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string MPAY
        {
            get
            {
                return this.mPAYField;
            }
            set
            {
                this.mPAYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public System.Guid SubscriberId
        {
            get
            {
                return this.subscriberIdField;
            }
            set
            {
                this.subscriberIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string PIN
        {
            get
            {
                return this.pINField;
            }
            set
            {
                this.pINField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=11)]
        public MMicroPaymentOutput1[] MicroPaymentResults
        {
            get
            {
                return this.microPaymentResultsField;
            }
            set
            {
                this.microPaymentResultsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int StatusCode
        {
            get
            {
                return this.statusCodeField;
            }
            set
            {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string ErrorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string ErrorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.mikro-odeme.com/")]
    public partial class CreditCardProxyData
    {
        
        private string creditCardNumberField;
        
        private int creditCardExpireMonthField;
        
        private int creditCardExpireYearField;
        
        private string creditCardOwnerField;
        
        private string cVVField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CreditCardNumber
        {
            get
            {
                return this.creditCardNumberField;
            }
            set
            {
                this.creditCardNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int CreditCardExpireMonth
        {
            get
            {
                return this.creditCardExpireMonthField;
            }
            set
            {
                this.creditCardExpireMonthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int CreditCardExpireYear
        {
            get
            {
                return this.creditCardExpireYearField;
            }
            set
            {
                this.creditCardExpireYearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string CreditCardOwner
        {
            get
            {
                return this.creditCardOwnerField;
            }
            set
            {
                this.creditCardOwnerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string CVV
        {
            get
            {
                return this.cVVField;
            }
            set
            {
                this.cVVField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="MSaleProduct", Namespace="http://services.mikro-odeme.com/")]
    public partial class MSaleProduct1
    {
        
        private int productIdField;
        
        private int productCategoryField;
        
        private string productDescriptionField;
        
        private double priceField;
        
        private int unitField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ProductId
        {
            get
            {
                return this.productIdField;
            }
            set
            {
                this.productIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int ProductCategory
        {
            get
            {
                return this.productCategoryField;
            }
            set
            {
                this.productCategoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ProductDescription
        {
            get
            {
                return this.productDescriptionField;
            }
            set
            {
                this.productDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public double Price
        {
            get
            {
                return this.priceField;
            }
            set
            {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int Unit
        {
            get
            {
                return this.unitField;
            }
            set
            {
                this.unitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CreditCardProxyInput))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="MSaleInput", Namespace="http://services.mikro-odeme.com/")]
    public partial class MSaleInput1
    {
        
        private string mPAYField;
        
        private string gsmField;
        
        private string contentField;
        
        private bool sendOrderResultField;
        
        private int paymentTypeIdField;
        
        private string urlField;
        
        private MSaleProduct1[] productListField;
        
        private System.Guid receivedSMSObjectIdField;
        
        private bool sendNotificationSMSField;
        
        private string onSuccessfulSMSField;
        
        private string onErrorSMSField;
        
        private int requestGsmOperatorField;
        
        private int requestGsmTypeField;
        
        private string turkcellServiceIdField;
        
        private string extraField;
        
        private string customerIpAddressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MPAY
        {
            get
            {
                return this.mPAYField;
            }
            set
            {
                this.mPAYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Gsm
        {
            get
            {
                return this.gsmField;
            }
            set
            {
                this.gsmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Content
        {
            get
            {
                return this.contentField;
            }
            set
            {
                this.contentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool SendOrderResult
        {
            get
            {
                return this.sendOrderResultField;
            }
            set
            {
                this.sendOrderResultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int PaymentTypeId
        {
            get
            {
                return this.paymentTypeIdField;
            }
            set
            {
                this.paymentTypeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Url
        {
            get
            {
                return this.urlField;
            }
            set
            {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
        public MSaleProduct1[] ProductList
        {
            get
            {
                return this.productListField;
            }
            set
            {
                this.productListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public System.Guid ReceivedSMSObjectId
        {
            get
            {
                return this.receivedSMSObjectIdField;
            }
            set
            {
                this.receivedSMSObjectIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public bool SendNotificationSMS
        {
            get
            {
                return this.sendNotificationSMSField;
            }
            set
            {
                this.sendNotificationSMSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string OnSuccessfulSMS
        {
            get
            {
                return this.onSuccessfulSMSField;
            }
            set
            {
                this.onSuccessfulSMSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string OnErrorSMS
        {
            get
            {
                return this.onErrorSMSField;
            }
            set
            {
                this.onErrorSMSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int RequestGsmOperator
        {
            get
            {
                return this.requestGsmOperatorField;
            }
            set
            {
                this.requestGsmOperatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int RequestGsmType
        {
            get
            {
                return this.requestGsmTypeField;
            }
            set
            {
                this.requestGsmTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string TurkcellServiceId
        {
            get
            {
                return this.turkcellServiceIdField;
            }
            set
            {
                this.turkcellServiceIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Extra
        {
            get
            {
                return this.extraField;
            }
            set
            {
                this.extraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string CustomerIpAddress
        {
            get
            {
                return this.customerIpAddressField;
            }
            set
            {
                this.customerIpAddressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.mikro-odeme.com/")]
    public partial class CreditCardProxyInput : MSaleInput1
    {
        
        private CreditCardProxyData dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CreditCardProxyData Data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="MAuthToken", Namespace="http://services.mikro-odeme.com/")]
    public partial class MAuthToken1
    {
        
        private string userCodeField;
        
        private string pinField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserCode
        {
            get
            {
                return this.userCodeField;
            }
            set
            {
                this.userCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Pin
        {
            get
            {
                return this.pinField;
            }
            set
            {
                this.pinField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TicketOutput))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.3pay.com/services/")]
    public partial class MResult
    {
        
        private int statusCodeField;
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int StatusCode
        {
            get
            {
                return this.statusCodeField;
            }
            set
            {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ErrorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ErrorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.3pay.com/services/")]
    public partial class TicketOutput : MResult
    {
        
        private string redirectUrlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string RedirectUrl
        {
            get
            {
                return this.redirectUrlField;
            }
            set
            {
                this.redirectUrlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.3pay.com/services/")]
    public partial class MSaleTicketOutput
    {
        
        private System.Guid ticketObjectIdField;
        
        private System.DateTime transactionDateField;
        
        private int statusCodeField;
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        private string redirectUrlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid TicketObjectId
        {
            get
            {
                return this.ticketObjectIdField;
            }
            set
            {
                this.ticketObjectIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime TransactionDate
        {
            get
            {
                return this.transactionDateField;
            }
            set
            {
                this.transactionDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int StatusCode
        {
            get
            {
                return this.statusCodeField;
            }
            set
            {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ErrorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ErrorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string RedirectUrl
        {
            get
            {
                return this.redirectUrlField;
            }
            set
            {
                this.redirectUrlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MSaleTicketInputExtended))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.3pay.com/services/")]
    public partial class MSaleTicketInput
    {
        
        private string mPAYField;
        
        private string contentField;
        
        private bool sendOrderResultField;
        
        private int paymentTypeIdField;
        
        private System.Guid receivedSMSObjectIdField;
        
        private MSaleProduct[] productListField;
        
        private bool sendNotificationSMSField;
        
        private string onSuccessfulSMSField;
        
        private string onErrorSMSField;
        
        private int requestGsmOperatorField;
        
        private int requestGsmTypeField;
        
        private string urlField;
        
        private string successfulPageUrlField;
        
        private string errorPageUrlField;
        
        private string countryField;
        
        private string currencyField;
        
        private string extraField;
        
        private string turkcellServiceIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MPAY
        {
            get
            {
                return this.mPAYField;
            }
            set
            {
                this.mPAYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Content
        {
            get
            {
                return this.contentField;
            }
            set
            {
                this.contentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool SendOrderResult
        {
            get
            {
                return this.sendOrderResultField;
            }
            set
            {
                this.sendOrderResultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int PaymentTypeId
        {
            get
            {
                return this.paymentTypeIdField;
            }
            set
            {
                this.paymentTypeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.Guid ReceivedSMSObjectId
        {
            get
            {
                return this.receivedSMSObjectIdField;
            }
            set
            {
                this.receivedSMSObjectIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        public MSaleProduct[] ProductList
        {
            get
            {
                return this.productListField;
            }
            set
            {
                this.productListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public bool SendNotificationSMS
        {
            get
            {
                return this.sendNotificationSMSField;
            }
            set
            {
                this.sendNotificationSMSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string OnSuccessfulSMS
        {
            get
            {
                return this.onSuccessfulSMSField;
            }
            set
            {
                this.onSuccessfulSMSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string OnErrorSMS
        {
            get
            {
                return this.onErrorSMSField;
            }
            set
            {
                this.onErrorSMSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int RequestGsmOperator
        {
            get
            {
                return this.requestGsmOperatorField;
            }
            set
            {
                this.requestGsmOperatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int RequestGsmType
        {
            get
            {
                return this.requestGsmTypeField;
            }
            set
            {
                this.requestGsmTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Url
        {
            get
            {
                return this.urlField;
            }
            set
            {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string SuccessfulPageUrl
        {
            get
            {
                return this.successfulPageUrlField;
            }
            set
            {
                this.successfulPageUrlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string ErrorPageUrl
        {
            get
            {
                return this.errorPageUrlField;
            }
            set
            {
                this.errorPageUrlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string Currency
        {
            get
            {
                return this.currencyField;
            }
            set
            {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string Extra
        {
            get
            {
                return this.extraField;
            }
            set
            {
                this.extraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string TurkcellServiceId
        {
            get
            {
                return this.turkcellServiceIdField;
            }
            set
            {
                this.turkcellServiceIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.3pay.com/services/")]
    public partial class MSaleTicketInputExtended : MSaleTicketInput
    {
        
        private string msisdnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Msisdn
        {
            get
            {
                return this.msisdnField;
            }
            set
            {
                this.msisdnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.3pay.com/services/")]
    public partial class QueryResultItem
    {
        
        private System.Guid orderObjectIdField;
        
        private string gsmField;
        
        private int gsmOperatorField;
        
        private int gsmTypeField;
        
        private int stateField;
        
        private double basePriceField;
        
        private System.DateTime lastTransactionDateField;
        
        private int paymentCategoryIdField;
        
        private int orderChannelIdField;
        
        private System.Guid subscriberIdField;
        
        private string pINField;
        
        private string mPAYField;
        
        private int statusCodeField;
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        private string contentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid OrderObjectId
        {
            get
            {
                return this.orderObjectIdField;
            }
            set
            {
                this.orderObjectIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Gsm
        {
            get
            {
                return this.gsmField;
            }
            set
            {
                this.gsmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int GsmOperator
        {
            get
            {
                return this.gsmOperatorField;
            }
            set
            {
                this.gsmOperatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int GsmType
        {
            get
            {
                return this.gsmTypeField;
            }
            set
            {
                this.gsmTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int State
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public double BasePrice
        {
            get
            {
                return this.basePriceField;
            }
            set
            {
                this.basePriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.DateTime LastTransactionDate
        {
            get
            {
                return this.lastTransactionDateField;
            }
            set
            {
                this.lastTransactionDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int PaymentCategoryId
        {
            get
            {
                return this.paymentCategoryIdField;
            }
            set
            {
                this.paymentCategoryIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int OrderChannelId
        {
            get
            {
                return this.orderChannelIdField;
            }
            set
            {
                this.orderChannelIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public System.Guid SubscriberId
        {
            get
            {
                return this.subscriberIdField;
            }
            set
            {
                this.subscriberIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string PIN
        {
            get
            {
                return this.pINField;
            }
            set
            {
                this.pINField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string MPAY
        {
            get
            {
                return this.mPAYField;
            }
            set
            {
                this.mPAYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int StatusCode
        {
            get
            {
                return this.statusCodeField;
            }
            set
            {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string ErrorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string ErrorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string Content
        {
            get
            {
                return this.contentField;
            }
            set
            {
                this.contentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.3pay.com/services/")]
    public partial class MQueryOutput
    {
        
        private int statusCodeField;
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        private QueryResultItem[] queryResultItemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int StatusCode
        {
            get
            {
                return this.statusCodeField;
            }
            set
            {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ErrorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ErrorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public QueryResultItem[] QueryResultItems
        {
            get
            {
                return this.queryResultItemsField;
            }
            set
            {
                this.queryResultItemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.3pay.com/services/")]
    public partial class MQueryInput
    {
        
        private string gsmField;
        
        private System.DateTime beginDateField;
        
        private System.DateTime endDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Gsm
        {
            get
            {
                return this.gsmField;
            }
            set
            {
                this.gsmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime BeginDate
        {
            get
            {
                return this.beginDateField;
            }
            set
            {
                this.beginDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime EndDate
        {
            get
            {
                return this.endDateField;
            }
            set
            {
                this.endDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.3pay.com/services/")]
    public partial class MSaleResult
    {
        
        private System.Guid orderObjectIdField;
        
        private string gsmField;
        
        private int gsmOperatorField;
        
        private int gsmTypeField;
        
        private int stateField;
        
        private int orderChannelIdField;
        
        private int paymentCategoryIdField;
        
        private System.DateTime lastTransactionDateField;
        
        private string mPAYField;
        
        private System.Guid subscriberIdField;
        
        private string pINField;
        
        private MMicroPaymentOutput[] microPaymentResultsField;
        
        private int statusCodeField;
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        private double basePriceField;
        
        private MSaleProduct[] productsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid OrderObjectId
        {
            get
            {
                return this.orderObjectIdField;
            }
            set
            {
                this.orderObjectIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Gsm
        {
            get
            {
                return this.gsmField;
            }
            set
            {
                this.gsmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int GsmOperator
        {
            get
            {
                return this.gsmOperatorField;
            }
            set
            {
                this.gsmOperatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int GsmType
        {
            get
            {
                return this.gsmTypeField;
            }
            set
            {
                this.gsmTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int State
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int OrderChannelId
        {
            get
            {
                return this.orderChannelIdField;
            }
            set
            {
                this.orderChannelIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int PaymentCategoryId
        {
            get
            {
                return this.paymentCategoryIdField;
            }
            set
            {
                this.paymentCategoryIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public System.DateTime LastTransactionDate
        {
            get
            {
                return this.lastTransactionDateField;
            }
            set
            {
                this.lastTransactionDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string MPAY
        {
            get
            {
                return this.mPAYField;
            }
            set
            {
                this.mPAYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public System.Guid SubscriberId
        {
            get
            {
                return this.subscriberIdField;
            }
            set
            {
                this.subscriberIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string PIN
        {
            get
            {
                return this.pINField;
            }
            set
            {
                this.pINField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=11)]
        public MMicroPaymentOutput[] MicroPaymentResults
        {
            get
            {
                return this.microPaymentResultsField;
            }
            set
            {
                this.microPaymentResultsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int StatusCode
        {
            get
            {
                return this.statusCodeField;
            }
            set
            {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string ErrorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string ErrorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public double BasePrice
        {
            get
            {
                return this.basePriceField;
            }
            set
            {
                this.basePriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=16)]
        public MSaleProduct[] Products
        {
            get
            {
                return this.productsField;
            }
            set
            {
                this.productsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.3pay.com/services/")]
    public partial class MMicroPaymentOutput
    {
        
        private System.Guid paymentObjectIdField;
        
        private int statusCodeField;
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        private string extraDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid PaymentObjectId
        {
            get
            {
                return this.paymentObjectIdField;
            }
            set
            {
                this.paymentObjectIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int StatusCode
        {
            get
            {
                return this.statusCodeField;
            }
            set
            {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ErrorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ErrorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ExtraData
        {
            get
            {
                return this.extraDataField;
            }
            set
            {
                this.extraDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MSaleOutputCreditCard))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.3pay.com/services/")]
    public partial class MSaleOutput
    {
        
        private System.Guid orderObjectIdField;
        
        private string gsmField;
        
        private int gsmOperatorField;
        
        private int gsmTypeField;
        
        private int stateField;
        
        private int orderChannelIdField;
        
        private int paymentCategoryIdField;
        
        private System.DateTime lastTransactionDateField;
        
        private string mPAYField;
        
        private System.Guid subscriberIdField;
        
        private string pINField;
        
        private MMicroPaymentOutput[] microPaymentResultsField;
        
        private int statusCodeField;
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid OrderObjectId
        {
            get
            {
                return this.orderObjectIdField;
            }
            set
            {
                this.orderObjectIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Gsm
        {
            get
            {
                return this.gsmField;
            }
            set
            {
                this.gsmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int GsmOperator
        {
            get
            {
                return this.gsmOperatorField;
            }
            set
            {
                this.gsmOperatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int GsmType
        {
            get
            {
                return this.gsmTypeField;
            }
            set
            {
                this.gsmTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int State
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int OrderChannelId
        {
            get
            {
                return this.orderChannelIdField;
            }
            set
            {
                this.orderChannelIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int PaymentCategoryId
        {
            get
            {
                return this.paymentCategoryIdField;
            }
            set
            {
                this.paymentCategoryIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public System.DateTime LastTransactionDate
        {
            get
            {
                return this.lastTransactionDateField;
            }
            set
            {
                this.lastTransactionDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string MPAY
        {
            get
            {
                return this.mPAYField;
            }
            set
            {
                this.mPAYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public System.Guid SubscriberId
        {
            get
            {
                return this.subscriberIdField;
            }
            set
            {
                this.subscriberIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string PIN
        {
            get
            {
                return this.pINField;
            }
            set
            {
                this.pINField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=11)]
        public MMicroPaymentOutput[] MicroPaymentResults
        {
            get
            {
                return this.microPaymentResultsField;
            }
            set
            {
                this.microPaymentResultsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int StatusCode
        {
            get
            {
                return this.statusCodeField;
            }
            set
            {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string ErrorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string ErrorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.3pay.com/services/")]
    public partial class MSaleOutputCreditCard : MSaleOutput
    {
        
        private double basePriceField;
        
        private System.Guid sessionObjectIdField;
        
        private string extraParamField;
        
        private System.Guid creditCardObjectIdField;
        
        private string maskedCreditCardNumberField;
        
        private string errorURLField;
        
        private string successURLField;
        
        private int cCSaleTypeIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public double BasePrice
        {
            get
            {
                return this.basePriceField;
            }
            set
            {
                this.basePriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.Guid SessionObjectId
        {
            get
            {
                return this.sessionObjectIdField;
            }
            set
            {
                this.sessionObjectIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ExtraParam
        {
            get
            {
                return this.extraParamField;
            }
            set
            {
                this.extraParamField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.Guid CreditCardObjectId
        {
            get
            {
                return this.creditCardObjectIdField;
            }
            set
            {
                this.creditCardObjectIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string MaskedCreditCardNumber
        {
            get
            {
                return this.maskedCreditCardNumberField;
            }
            set
            {
                this.maskedCreditCardNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ErrorURL
        {
            get
            {
                return this.errorURLField;
            }
            set
            {
                this.errorURLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string SuccessURL
        {
            get
            {
                return this.successURLField;
            }
            set
            {
                this.successURLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int CCSaleTypeId
        {
            get
            {
                return this.cCSaleTypeIdField;
            }
            set
            {
                this.cCSaleTypeIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.3pay.com/services/")]
    public partial class MSaleInput
    {
        
        private string mPAYField;
        
        private string gsmField;
        
        private string contentField;
        
        private bool sendOrderResultField;
        
        private int paymentTypeIdField;
        
        private string urlField;
        
        private MSaleProduct[] productListField;
        
        private System.Guid receivedSMSObjectIdField;
        
        private bool sendNotificationSMSField;
        
        private string onSuccessfulSMSField;
        
        private string onErrorSMSField;
        
        private int requestGsmOperatorField;
        
        private int requestGsmTypeField;
        
        private string turkcellServiceIdField;
        
        private string extraField;
        
        private string customerIpAddressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MPAY
        {
            get
            {
                return this.mPAYField;
            }
            set
            {
                this.mPAYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Gsm
        {
            get
            {
                return this.gsmField;
            }
            set
            {
                this.gsmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Content
        {
            get
            {
                return this.contentField;
            }
            set
            {
                this.contentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool SendOrderResult
        {
            get
            {
                return this.sendOrderResultField;
            }
            set
            {
                this.sendOrderResultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int PaymentTypeId
        {
            get
            {
                return this.paymentTypeIdField;
            }
            set
            {
                this.paymentTypeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Url
        {
            get
            {
                return this.urlField;
            }
            set
            {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
        public MSaleProduct[] ProductList
        {
            get
            {
                return this.productListField;
            }
            set
            {
                this.productListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public System.Guid ReceivedSMSObjectId
        {
            get
            {
                return this.receivedSMSObjectIdField;
            }
            set
            {
                this.receivedSMSObjectIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public bool SendNotificationSMS
        {
            get
            {
                return this.sendNotificationSMSField;
            }
            set
            {
                this.sendNotificationSMSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string OnSuccessfulSMS
        {
            get
            {
                return this.onSuccessfulSMSField;
            }
            set
            {
                this.onSuccessfulSMSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string OnErrorSMS
        {
            get
            {
                return this.onErrorSMSField;
            }
            set
            {
                this.onErrorSMSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int RequestGsmOperator
        {
            get
            {
                return this.requestGsmOperatorField;
            }
            set
            {
                this.requestGsmOperatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int RequestGsmType
        {
            get
            {
                return this.requestGsmTypeField;
            }
            set
            {
                this.requestGsmTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string TurkcellServiceId
        {
            get
            {
                return this.turkcellServiceIdField;
            }
            set
            {
                this.turkcellServiceIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Extra
        {
            get
            {
                return this.extraField;
            }
            set
            {
                this.extraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string CustomerIpAddress
        {
            get
            {
                return this.customerIpAddressField;
            }
            set
            {
                this.customerIpAddressField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface SaleServiceSoapChannel : SaleService.SaleServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class SaleServiceSoapClient : System.ServiceModel.ClientBase<SaleService.SaleServiceSoap>, SaleService.SaleServiceSoap
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SaleServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(SaleServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), SaleServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SaleServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SaleServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SaleServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SaleServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SaleServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<SaleService.MSaleOutput> SaleWithConfirmAsync(SaleService.MAuthToken token, SaleService.MSaleInput input)
        {
            return base.Channel.SaleWithConfirmAsync(token, input);
        }
        
        public System.Threading.Tasks.Task<SaleService.MSaleOutput> SaleWithoutConfirmAsync(SaleService.MAuthToken token, SaleService.MSaleInput input)
        {
            return base.Channel.SaleWithoutConfirmAsync(token, input);
        }
        
        public System.Threading.Tasks.Task<SaleService.MSaleOutput> SaleWithoutConfirmTestAsync(SaleService.MAuthToken token, SaleService.MSaleInput input)
        {
            return base.Channel.SaleWithoutConfirmTestAsync(token, input);
        }
        
        public System.Threading.Tasks.Task<SaleService.MSaleOutput> GetSaleResultAsync(SaleService.MAuthToken token, System.Guid orderId)
        {
            return base.Channel.GetSaleResultAsync(token, orderId);
        }
        
        public System.Threading.Tasks.Task<SaleService.MSaleOutput> GetSaleResultMPAYAsync(SaleService.MAuthToken token, string MPAY)
        {
            return base.Channel.GetSaleResultMPAYAsync(token, MPAY);
        }
        
        public System.Threading.Tasks.Task<SaleService.MSaleResult> GetSaleResult2Async(SaleService.MAuthToken token, System.Guid orderId)
        {
            return base.Channel.GetSaleResult2Async(token, orderId);
        }
        
        public System.Threading.Tasks.Task<SaleService.MQueryOutput> QueryMicroPaymentsAsync(SaleService.MAuthToken token, SaleService.MQueryInput input)
        {
            return base.Channel.QueryMicroPaymentsAsync(token, input);
        }
        
        public System.Threading.Tasks.Task<SaleService.MSaleTicketOutput> SaleWithTicketAsync(SaleService.MAuthToken token, SaleService.MSaleTicketInput input)
        {
            return base.Channel.SaleWithTicketAsync(token, input);
        }
        
        public System.Threading.Tasks.Task<SaleService.MSaleTicketOutput> SaleWithTicketMPAsync(SaleService.MAuthToken token, SaleService.MSaleTicketInputExtended input)
        {
            return base.Channel.SaleWithTicketMPAsync(token, input);
        }
        
        public System.Threading.Tasks.Task<SaleService.MResult> CancelTicketAsync(SaleService.MAuthToken token, System.Guid ticketObjectId)
        {
            return base.Channel.CancelTicketAsync(token, ticketObjectId);
        }
        
        public System.Threading.Tasks.Task<SaleService.MResult> CheckTicketAsync(SaleService.MAuthToken token, System.Guid ticketObjectId)
        {
            return base.Channel.CheckTicketAsync(token, ticketObjectId);
        }
        
        public System.Threading.Tasks.Task<string> GetBokuPricePointsAsync(string country)
        {
            return base.Channel.GetBokuPricePointsAsync(country);
        }
        
        public System.Threading.Tasks.Task<SaleService.MSaleOutput1> CreditCardProxyAsync(SaleService.MAuthToken1 token, SaleService.CreditCardProxyInput input)
        {
            return base.Channel.CreditCardProxyAsync(token, input);
        }
        
        public System.Threading.Tasks.Task<SaleService.MSaleOutput> StartSaleWithOtpAsync(SaleService.MAuthToken token, SaleService.MSaleInput input)
        {
            return base.Channel.StartSaleWithOtpAsync(token, input);
        }
        
        public System.Threading.Tasks.Task<SaleService.MSaleOutput> ResumeSaleWithOtpAsync(SaleService.MAuthToken token, System.Guid orderId, string otp)
        {
            return base.Channel.ResumeSaleWithOtpAsync(token, orderId, otp);
        }
        
        public System.Threading.Tasks.Task<SaleService.TicketOutput> CreateTicketForMsisdnForwardingAsync(SaleService.MAuthToken token, string redirectUrl)
        {
            return base.Channel.CreateTicketForMsisdnForwardingAsync(token, redirectUrl);
        }
        
        public System.Threading.Tasks.Task<SaleService.MSaleOutputCreditCard> StartSubscriptionWithTokenAsync(SaleService.MAuthToken token, SaleService.MTokenSaleInput input)
        {
            return base.Channel.StartSubscriptionWithTokenAsync(token, input);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SaleServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.SaleServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SaleServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://www.wirecard.com.tr/services/saleservice.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.SaleServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://www.wirecard.com.tr/services/saleservice.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            SaleServiceSoap,
            
            SaleServiceSoap12,
        }
    }
}
