//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.3pay.com/services/", ConfigurationName="ApiService.SubscriberManagementServiceSoap")]
    public interface SubscriberManagementServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.3pay.com/services/DeactivateSubscriber", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ApiService.MOperationOutput> DeactivateSubscriberAsync(ApiService.MAuthToken token, System.Guid subscriberId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.3pay.com/services/DeleteSubscriber", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ApiService.MOperationOutput> DeleteSubscriberAsync(ApiService.MAuthToken token, System.Guid subscriberId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.3pay.com/services/SelectSubscriber", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ApiService.MSelectSubscriberOutput> SelectSubscriberAsync(ApiService.MAuthToken token, ApiService.MSelectSubscriberInput input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.3pay.com/services/SelectSubscriberDetail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ApiService.MSubscriberDetailOutput> SelectSubscriberDetailAsync(ApiService.MAuthToken token, System.Guid subscriberId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.3pay.com/services/UpdateSubscriberPriceByIdandDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ApiService.MResult> UpdateSubscriberPriceByIdandDateAsync(ApiService.MAuthToken token, System.Guid serviceSubscriberId, System.DateTime validFrom, double newPrice, string description);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.3pay.com/services/")]
    public partial class MAuthToken
    {
        
        private string userCodeField;
        
        private string pinField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserCode
        {
            get
            {
                return this.userCodeField;
            }
            set
            {
                this.userCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Pin
        {
            get
            {
                return this.pinField;
            }
            set
            {
                this.pinField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.3pay.com/services/")]
    public partial class MResult
    {
        
        private int statusCodeField;
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int StatusCode
        {
            get
            {
                return this.statusCodeField;
            }
            set
            {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ErrorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ErrorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.3pay.com/services/")]
    public partial class MSubscriberPayment
    {
        
        private System.DateTime paymentDateField;
        
        private bool isPaidField;
        
        private System.Guid orderObjectIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime PaymentDate
        {
            get
            {
                return this.paymentDateField;
            }
            set
            {
                this.paymentDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool IsPaid
        {
            get
            {
                return this.isPaidField;
            }
            set
            {
                this.isPaidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.Guid OrderObjectId
        {
            get
            {
                return this.orderObjectIdField;
            }
            set
            {
                this.orderObjectIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.3pay.com/services/")]
    public partial class MSubscriberDetail
    {
        
        private System.Guid subscriberIdField;
        
        private string gSMField;
        
        private System.DateTime startDateField;
        
        private int subscriberTypeIdField;
        
        private int paymentCategoryIdField;
        
        private double basePriceField;
        
        private double baseUnitPriceField;
        
        private int productIdField;
        
        private string productNameField;
        
        private int orderChannelIdField;
        
        private System.DateTime lastSuccessfulPaymentDateField;
        
        private System.DateTime nextEstimatedPaymentDateField;
        
        private int gsmOperatorField;
        
        private bool activeField;
        
        private string cancelKeywordField;
        
        private MSubscriberPayment[] paymentsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid SubscriberId
        {
            get
            {
                return this.subscriberIdField;
            }
            set
            {
                this.subscriberIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string GSM
        {
            get
            {
                return this.gSMField;
            }
            set
            {
                this.gSMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime StartDate
        {
            get
            {
                return this.startDateField;
            }
            set
            {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int SubscriberTypeId
        {
            get
            {
                return this.subscriberTypeIdField;
            }
            set
            {
                this.subscriberTypeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int PaymentCategoryId
        {
            get
            {
                return this.paymentCategoryIdField;
            }
            set
            {
                this.paymentCategoryIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public double BasePrice
        {
            get
            {
                return this.basePriceField;
            }
            set
            {
                this.basePriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public double BaseUnitPrice
        {
            get
            {
                return this.baseUnitPriceField;
            }
            set
            {
                this.baseUnitPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int ProductId
        {
            get
            {
                return this.productIdField;
            }
            set
            {
                this.productIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string ProductName
        {
            get
            {
                return this.productNameField;
            }
            set
            {
                this.productNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int OrderChannelId
        {
            get
            {
                return this.orderChannelIdField;
            }
            set
            {
                this.orderChannelIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public System.DateTime LastSuccessfulPaymentDate
        {
            get
            {
                return this.lastSuccessfulPaymentDateField;
            }
            set
            {
                this.lastSuccessfulPaymentDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public System.DateTime NextEstimatedPaymentDate
        {
            get
            {
                return this.nextEstimatedPaymentDateField;
            }
            set
            {
                this.nextEstimatedPaymentDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int GsmOperator
        {
            get
            {
                return this.gsmOperatorField;
            }
            set
            {
                this.gsmOperatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public bool Active
        {
            get
            {
                return this.activeField;
            }
            set
            {
                this.activeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string CancelKeyword
        {
            get
            {
                return this.cancelKeywordField;
            }
            set
            {
                this.cancelKeywordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=15)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Payment")]
        public MSubscriberPayment[] Payments
        {
            get
            {
                return this.paymentsField;
            }
            set
            {
                this.paymentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.3pay.com/services/")]
    public partial class MSubscriberDetailOutput
    {
        
        private int statusCodeField;
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        private MSubscriberDetail subscriberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int StatusCode
        {
            get
            {
                return this.statusCodeField;
            }
            set
            {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ErrorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ErrorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public MSubscriberDetail Subscriber
        {
            get
            {
                return this.subscriberField;
            }
            set
            {
                this.subscriberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.3pay.com/services/")]
    public partial class MSubscriber
    {
        
        private System.Guid subscriberIdField;
        
        private string gSMField;
        
        private System.DateTime startDateField;
        
        private int subscriberTypeIdField;
        
        private int paymentCategoryIdField;
        
        private double basePriceField;
        
        private double baseUnitPriceField;
        
        private int productIdField;
        
        private string productNameField;
        
        private int orderChannelIdField;
        
        private bool activeField;
        
        private System.DateTime lastSuccessfulPaymentDateField;
        
        private int gsmOperatorField;
        
        private string cancelKeywordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid SubscriberId
        {
            get
            {
                return this.subscriberIdField;
            }
            set
            {
                this.subscriberIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string GSM
        {
            get
            {
                return this.gSMField;
            }
            set
            {
                this.gSMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime StartDate
        {
            get
            {
                return this.startDateField;
            }
            set
            {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int SubscriberTypeId
        {
            get
            {
                return this.subscriberTypeIdField;
            }
            set
            {
                this.subscriberTypeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int PaymentCategoryId
        {
            get
            {
                return this.paymentCategoryIdField;
            }
            set
            {
                this.paymentCategoryIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public double BasePrice
        {
            get
            {
                return this.basePriceField;
            }
            set
            {
                this.basePriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public double BaseUnitPrice
        {
            get
            {
                return this.baseUnitPriceField;
            }
            set
            {
                this.baseUnitPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int ProductId
        {
            get
            {
                return this.productIdField;
            }
            set
            {
                this.productIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string ProductName
        {
            get
            {
                return this.productNameField;
            }
            set
            {
                this.productNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int OrderChannelId
        {
            get
            {
                return this.orderChannelIdField;
            }
            set
            {
                this.orderChannelIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public bool Active
        {
            get
            {
                return this.activeField;
            }
            set
            {
                this.activeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public System.DateTime LastSuccessfulPaymentDate
        {
            get
            {
                return this.lastSuccessfulPaymentDateField;
            }
            set
            {
                this.lastSuccessfulPaymentDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int GsmOperator
        {
            get
            {
                return this.gsmOperatorField;
            }
            set
            {
                this.gsmOperatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string CancelKeyword
        {
            get
            {
                return this.cancelKeywordField;
            }
            set
            {
                this.cancelKeywordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.3pay.com/services/")]
    public partial class MSelectSubscriberOutput
    {
        
        private int statusCodeField;
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        private MSubscriber[] subscribersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int StatusCode
        {
            get
            {
                return this.statusCodeField;
            }
            set
            {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ErrorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ErrorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Subscriber")]
        public MSubscriber[] Subscribers
        {
            get
            {
                return this.subscribersField;
            }
            set
            {
                this.subscribersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.3pay.com/services/")]
    public partial class MSelectSubscriberInput
    {
        
        private int productIdField;
        
        private string gSMField;
        
        private int orderChannelIdField;
        
        private int activeField;
        
        private int subscriberTypeField;
        
        private System.DateTime startDateMinField;
        
        private System.DateTime startDateMaxField;
        
        private System.DateTime lastSuccessfulPaymentDateMinField;
        
        private System.DateTime lastSuccessfulPaymentDateMaxField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ProductId
        {
            get
            {
                return this.productIdField;
            }
            set
            {
                this.productIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string GSM
        {
            get
            {
                return this.gSMField;
            }
            set
            {
                this.gSMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int OrderChannelId
        {
            get
            {
                return this.orderChannelIdField;
            }
            set
            {
                this.orderChannelIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Active
        {
            get
            {
                return this.activeField;
            }
            set
            {
                this.activeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int SubscriberType
        {
            get
            {
                return this.subscriberTypeField;
            }
            set
            {
                this.subscriberTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.DateTime StartDateMin
        {
            get
            {
                return this.startDateMinField;
            }
            set
            {
                this.startDateMinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.DateTime StartDateMax
        {
            get
            {
                return this.startDateMaxField;
            }
            set
            {
                this.startDateMaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public System.DateTime LastSuccessfulPaymentDateMin
        {
            get
            {
                return this.lastSuccessfulPaymentDateMinField;
            }
            set
            {
                this.lastSuccessfulPaymentDateMinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public System.DateTime LastSuccessfulPaymentDateMax
        {
            get
            {
                return this.lastSuccessfulPaymentDateMaxField;
            }
            set
            {
                this.lastSuccessfulPaymentDateMaxField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.3pay.com/services/")]
    public partial class MOperationOutput
    {
        
        private int statusCodeField;
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int StatusCode
        {
            get
            {
                return this.statusCodeField;
            }
            set
            {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ErrorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ErrorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface SubscriberManagementServiceSoapChannel : ApiService.SubscriberManagementServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class SubscriberManagementServiceSoapClient : System.ServiceModel.ClientBase<ApiService.SubscriberManagementServiceSoap>, ApiService.SubscriberManagementServiceSoap
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SubscriberManagementServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(SubscriberManagementServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), SubscriberManagementServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SubscriberManagementServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SubscriberManagementServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SubscriberManagementServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SubscriberManagementServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SubscriberManagementServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ApiService.MOperationOutput> DeactivateSubscriberAsync(ApiService.MAuthToken token, System.Guid subscriberId)
        {
            return base.Channel.DeactivateSubscriberAsync(token, subscriberId);
        }
        
        public System.Threading.Tasks.Task<ApiService.MOperationOutput> DeleteSubscriberAsync(ApiService.MAuthToken token, System.Guid subscriberId)
        {
            return base.Channel.DeleteSubscriberAsync(token, subscriberId);
        }
        
        public System.Threading.Tasks.Task<ApiService.MSelectSubscriberOutput> SelectSubscriberAsync(ApiService.MAuthToken token, ApiService.MSelectSubscriberInput input)
        {
            return base.Channel.SelectSubscriberAsync(token, input);
        }
        
        public System.Threading.Tasks.Task<ApiService.MSubscriberDetailOutput> SelectSubscriberDetailAsync(ApiService.MAuthToken token, System.Guid subscriberId)
        {
            return base.Channel.SelectSubscriberDetailAsync(token, subscriberId);
        }
        
        public System.Threading.Tasks.Task<ApiService.MResult> UpdateSubscriberPriceByIdandDateAsync(ApiService.MAuthToken token, System.Guid serviceSubscriberId, System.DateTime validFrom, double newPrice, string description)
        {
            return base.Channel.UpdateSubscriberPriceByIdandDateAsync(token, serviceSubscriberId, validFrom, newPrice, description);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SubscriberManagementServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.SubscriberManagementServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SubscriberManagementServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://www.3pay.com/services/SubscriberManagementService.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.SubscriberManagementServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://www.3pay.com/services/SubscriberManagementService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            SubscriberManagementServiceSoap,
            
            SubscriberManagementServiceSoap12,
        }
    }
}
