//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SendInformationSMSService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MAuthToken", Namespace="http://services.mikro-odeme.com/")]
    public partial class MAuthToken : object
    {
        
        private string UserCodeField;
        
        private string PinField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserCode
        {
            get
            {
                return this.UserCodeField;
            }
            set
            {
                this.UserCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Pin
        {
            get
            {
                return this.PinField;
            }
            set
            {
                this.PinField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MSendSMSInput", Namespace="http://services.mikro-odeme.com/")]
    public partial class MSendSMSInput : object
    {
        
        private string GsmField;
        
        private string ContentField;
        
        private int RequestGsmOperatorField;
        
        private int RequestGsmTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Gsm
        {
            get
            {
                return this.GsmField;
            }
            set
            {
                this.GsmField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Content
        {
            get
            {
                return this.ContentField;
            }
            set
            {
                this.ContentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int RequestGsmOperator
        {
            get
            {
                return this.RequestGsmOperatorField;
            }
            set
            {
                this.RequestGsmOperatorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int RequestGsmType
        {
            get
            {
                return this.RequestGsmTypeField;
            }
            set
            {
                this.RequestGsmTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MSendSMSOutput", Namespace="http://services.mikro-odeme.com/")]
    public partial class MSendSMSOutput : object
    {
        
        private string SendSMSObjectIdField;
        
        private int StatusCodeField;
        
        private string ErrorCodeField;
        
        private string ErrorMessageField;
        
        private int GsmOperatorField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string SendSMSObjectId
        {
            get
            {
                return this.SendSMSObjectIdField;
            }
            set
            {
                this.SendSMSObjectIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int StatusCode
        {
            get
            {
                return this.StatusCodeField;
            }
            set
            {
                this.StatusCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int GsmOperator
        {
            get
            {
                return this.GsmOperatorField;
            }
            set
            {
                this.GsmOperatorField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.mikro-odeme.com/", ConfigurationName="SendInformationSMSService.MSendSMSServiceSoap")]
    public interface MSendSMSServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.mikro-odeme.com/SendSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<SendInformationSMSService.SendSMSResponse> SendSMSAsync(SendInformationSMSService.SendSMSRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMS", Namespace="http://services.mikro-odeme.com/", Order=0)]
        public SendInformationSMSService.SendSMSRequestBody Body;
        
        public SendSMSRequest()
        {
        }
        
        public SendSMSRequest(SendInformationSMSService.SendSMSRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.mikro-odeme.com/")]
    public partial class SendSMSRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SendInformationSMSService.MAuthToken token;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public SendInformationSMSService.MSendSMSInput input;
        
        public SendSMSRequestBody()
        {
        }
        
        public SendSMSRequestBody(SendInformationSMSService.MAuthToken token, SendInformationSMSService.MSendSMSInput input)
        {
            this.token = token;
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMSResponse", Namespace="http://services.mikro-odeme.com/", Order=0)]
        public SendInformationSMSService.SendSMSResponseBody Body;
        
        public SendSMSResponse()
        {
        }
        
        public SendSMSResponse(SendInformationSMSService.SendSMSResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.mikro-odeme.com/")]
    public partial class SendSMSResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SendInformationSMSService.MSendSMSOutput SendSMSResult;
        
        public SendSMSResponseBody()
        {
        }
        
        public SendSMSResponseBody(SendInformationSMSService.MSendSMSOutput SendSMSResult)
        {
            this.SendSMSResult = SendSMSResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface MSendSMSServiceSoapChannel : SendInformationSMSService.MSendSMSServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class MSendSMSServiceSoapClient : System.ServiceModel.ClientBase<SendInformationSMSService.MSendSMSServiceSoap>, SendInformationSMSService.MSendSMSServiceSoap
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MSendSMSServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(MSendSMSServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), MSendSMSServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MSendSMSServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MSendSMSServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MSendSMSServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MSendSMSServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MSendSMSServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SendInformationSMSService.SendSMSResponse> SendInformationSMSService.MSendSMSServiceSoap.SendSMSAsync(SendInformationSMSService.SendSMSRequest request)
        {
            return base.Channel.SendSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<SendInformationSMSService.SendSMSResponse> SendSMSAsync(SendInformationSMSService.MAuthToken token, SendInformationSMSService.MSendSMSInput input)
        {
            SendInformationSMSService.SendSMSRequest inValue = new SendInformationSMSService.SendSMSRequest();
            inValue.Body = new SendInformationSMSService.SendSMSRequestBody();
            inValue.Body.token = token;
            inValue.Body.input = input;
            return ((SendInformationSMSService.MSendSMSServiceSoap)(this)).SendSMSAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MSendSMSServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.MSendSMSServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MSendSMSServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://vas.mikro-odeme.com/services/msendsmsservice.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.MSendSMSServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://vas.mikro-odeme.com/services/msendsmsservice.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            MSendSMSServiceSoap,
            
            MSendSMSServiceSoap12,
        }
    }
}
